GO
/****** Object:  StoredProcedure [dbo].[GetStats]    Script Date: 4/19/2017 2:12:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[GetStats]	
	@GameID int = null,
	@PlayerID int = null,
	@TeamID int = null,
	@LeagueID int = null
AS
BEGIN
	SET NOCOUNT ON;

	SELECT	S.ID, 
			S.StatTypeID,
			S.Value,
			S.GameID,
			S.PlayerID,
			S.TeamID,
			G.LeagueID,
			L.SportID,
			ST.DefaultShow,
			ST.DisplayName,
			ST.SelectionDisplayOrder,
            ST.GridDisplayOrder,
			ST.AutoGenerated,
			ST.ValueType,
			ST.IsCalculated,
			ST.Name,
			ST.ID as StatTypeID,
			S.StatGroup as GroupID
	FROM	dbo.[Stats] S
	JOIN	dbo.[StatTypes] ST
	ON		S.StatTypeID = ST.ID
	JOIN	Games G
	ON		G.ID = S.GameID
	JOIN	Leagues L 
	ON		L.ID = G.LeagueID
	WHERE	S.Deleted = 0
	AND		(@GameID is null OR S.GameID = @GameID)
	AND		(@PlayerID is null OR S.PlayerID = @PlayerID)
	AND		(@TeamID is null OR S.TeamID = @TeamID)
	AND		(@LeagueID is null OR G.LeagueID = @LeagueID)
    
    SELECT  SS.StatID,
            SS.GameID,
            S.PlayerID,
            SS.StateID,
			G.LeagueID
    FROM    StatStates SS
    JOIN    Stats S
    ON      SS.StatID = S.ID
	JOIN	Games G
	ON		G.ID = S.GameID
    WHERE   S.Deleted = 0
	AND		(@GameID is null OR S.GameID = @GameID)
	AND		(@PlayerID is null OR S.PlayerID = @PlayerID)
	AND		(@TeamID is null OR S.TeamID = @TeamID)
	AND		(@LeagueID is null OR G.LeagueID = @LeagueID)

END

