using System.Collections.Generic;

namespace SportsStats.Models.ControllerObjects
{
    public class StatsResult
    {
        public int PlayerNumber { get; set; }
        public int? PlayerID { get; set; }
        public string PlayerName { get; set; }
        public int? GroupID { get; set; }
		public int LeagueID { get; set; }
		public List<StatTypesResult> StatTypes { get; set; }
        public BaseballGameStateResult BaseballGameStateResult { get; set; }
        public List<StatGroupResult> StatGroups { get; set; }
        public GameResultBase GameResult { get; set; }
    }
    public class StatTypesResult
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public bool DefaultShow { get; set; }
        public decimal CurrentValue { get; set; }
        public int GridDisplayOrder { get; set; }
        public int SelectionDisplayOrder { get; set; }
        public bool AutoGenerated { get; set; }
    }
    public class StatRequest
    {
        public int StatTypeID { get; set; }
        public int? PlayerID { get; set; }
		public int LeagueID { get; set; }
		public int GameID { get; set; }
        public int TeamID { get; set; }
        public int Value { get; set; }
        public int? GroupID { get; set; }
        public bool IsLatestGroup { get; set; }
		public bool IsBaseball { get; set; }
	}
}