namespace SportsStats.Models.DTOObjects
{
    public class DTOStatType
    {
        public int SportID { get; set; }
        public int StatTypeID { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public bool DefaultShow { get; set; }
        public bool IsCalculated { get; set; }
        public int GridDisplayOrder { get; set; }
        public int SelectionDisplayOrder { get; set; }
        public int ValueType { get; set; }
        public int QuickButtonOrder { get; set; }
        public string QuickButtonText { get; set; }
        public bool IsPositive { get; set; }
        public bool AutoGenerated { get; set; }
        public bool ShowGame { get; set; }
        public bool ShowTeam { get; set; }
        public bool ShowPlayer { get; set; }
    }
}