using static SportsStats.Helpers.Enums;

namespace SportsStats.Models.ServiceObjects
{
    public class StatType
    {
        public int SportID { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public bool DefaultShow { get; set; }
        public bool IsCalculated { get; set; }
        public int GridDisplayOrder { get; set; }
        public int SelectionDisplayOrder { get; set; }
        public ValueTypes ValueType { get; set; }
        public bool IsPositive { get; set; }
        public int QuickButtonOrder { get; set; }
        public string QuickButtonText { get; set; }
        public bool AutoGenerated { get; set; }
    }
}